
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  # namespace: {{ .Values.todoapp.ns.name }}
spec:

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.requestStorage}}