{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name}}-monitor
  labels:
    release: kube-prometheus-stack
    app: todoapp
spec:
  namespaceSelector:
    matchNames:
      - todoapp
  selector:
    matchLabels:
      app: todoapp
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}