common:
  image: ikulyk404
  tag: 4.0.1


todoapp:
  ns:
    name: todoapp

secrets:
  SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
  DB_NAME: "app_db"
  DB_USER: "app_user"
  DB_PASSWORD: "1234"
  # DB_HOST: "mysql-0.mysql-headless.default.svc.cluster.local"
  DB_HOST: "mysql-0.mysql.mysql.svc.cluster.local"
resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "256Mi"
    cpu: "150m"


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

nodeAffinity:
  key: "app"
  value: "todoapp"

hpa:
  minReplicas: 2
  maxReplicas: 5
  cpu: 70
  memory: 70

pv:
  capacity: 1Gi

pvc:
 requestStorage: 1Gi

serviceAccountName: secrets-reader

serviceMonitor:
  enabled: true
  labels: {}
  interval: 10s
  path: /metrics
  port: http-metrics